# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ox_goldox_msg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ox_goldox_msg.proto',
  package='',
  serialized_pb='\n\x13ox_goldox_msg.proto\"+\n\x0eOX_GOLD_OX_MSG\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\x0b\n\x03uID\x18\x02 \x02(\x05\"\x93\x01\n\x12OX_GOLD_OX_RET_MSG\x12\x0c\n\x04nRet\x18\x01 \x02(\x05\x12\x0e\n\x06weight\x18\x02 \x01(\x02\x12\x0f\n\x07goldnum\x18\x03 \x01(\x03\x12\x10\n\x08nexttime\x18\x04 \x01(\x05\x12\x12\n\nmaxgoldnum\x18\x05 \x01(\x05\x12\x11\n\tsparetime\x18\x06 \x01(\x05\x12\x15\n\rdaymaxgoldnum\x18\x07 \x01(\x05')




_OX_GOLD_OX_MSG = _descriptor.Descriptor(
  name='OX_GOLD_OX_MSG',
  full_name='OX_GOLD_OX_MSG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='OX_GOLD_OX_MSG.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uID', full_name='OX_GOLD_OX_MSG.uID', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=66,
)


_OX_GOLD_OX_RET_MSG = _descriptor.Descriptor(
  name='OX_GOLD_OX_RET_MSG',
  full_name='OX_GOLD_OX_RET_MSG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nRet', full_name='OX_GOLD_OX_RET_MSG.nRet', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='OX_GOLD_OX_RET_MSG.weight', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goldnum', full_name='OX_GOLD_OX_RET_MSG.goldnum', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nexttime', full_name='OX_GOLD_OX_RET_MSG.nexttime', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxgoldnum', full_name='OX_GOLD_OX_RET_MSG.maxgoldnum', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sparetime', full_name='OX_GOLD_OX_RET_MSG.sparetime', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='daymaxgoldnum', full_name='OX_GOLD_OX_RET_MSG.daymaxgoldnum', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=69,
  serialized_end=216,
)

DESCRIPTOR.message_types_by_name['OX_GOLD_OX_MSG'] = _OX_GOLD_OX_MSG
DESCRIPTOR.message_types_by_name['OX_GOLD_OX_RET_MSG'] = _OX_GOLD_OX_RET_MSG

class OX_GOLD_OX_MSG(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OX_GOLD_OX_MSG

  # @@protoc_insertion_point(class_scope:OX_GOLD_OX_MSG)

class OX_GOLD_OX_RET_MSG(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OX_GOLD_OX_RET_MSG

  # @@protoc_insertion_point(class_scope:OX_GOLD_OX_RET_MSG)


# @@protoc_insertion_point(module_scope)
